# Uncomment the next line to define a global platform for your project
 platform :ios, '13.2'

target 'movcom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CollectionViewSlantedLayout', '~> 3.1'
  pod 'Alamofire', '~> 5.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
end
